[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ctsit_python_utils"
version = "0.1.0"
authors = [{ name = "Michael Bentz", email = "mbentz@ufl.edu" }]
description = ""
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

# We don't need this for now
# [project.scripts]
# package_name = "package_name.__main__:main"

[project.urls]
"Homepage" = "https://github.com/ctsit/ctsit_python_utils"
"Bug Tracker" = "https://github.com/ctsit/ctsit_python_utils/issues"
