name: lint

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  flake8-lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
